### PR TITLE
Updated

### PR DESCRIPTION
**Pull request by kabilan1290**
Xss hunter payload can be dervied from user input and used with dalfox.

https://medium.com/bugbountywriteup/automating-xss-using-dalfox-gf-and-waybackurls-bc6de16a5c75

As the blog describes dalfox file testxss.txt -b tigv2.xss.ht pipe, we can insert our payload using the -b flag.

./Quickxss target test.xss.ht ==> This would be a efficient formating.

Thanks.

### CODE REVIEW

**Review by theinfosecguy — COMMENTED** [review]
Have you tested this, If this works well? @kabilan1920 .

**Comment by kabilan1290** [comment]
Yes tested and working!

**Comment by kabilan1290** [comment]
I would like you to double check!

Thanks.

**Comment by theinfosecguy** [comment]
Thanks for contributing to QuickXSS ! @kabilan1290

**Pull request closed without merging**
